# Site settings
title: Aulin
description: Blog about tech stuff
url: 'http://aulin.co'
baseurl: /
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Erik AULIN'
  email: erik@aulin.co
  twitter_username: erikrpm
  facebook_username: erikaulin
  github_username:  erikaulin
  linkedin_username:  erikaulin

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
